server:
  port: 8085

spring:
  datasource:
    url: jdbc:sqlite:./data/toolsdb.db
    driver-class-name: org.sqlite.JDBC
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  plugins:
    dir: ./plugins
    max-size: 10485760
    max-files: 100
